version: "2"
services:

    toolinder:
        container_name: toolinder
        build: ./app
        restart: always
        ports:
        - 8080:8080
        environment:
        - VIRTUAL_HOST=api3.skoerner.com
        - VIRTUAL_PORT=8080
        - LETSENCRYPT_HOST=api3.skoerner.com
        - LETSENCRYPT_EMAIL=admin@skoerner.com
        - TZ=Europe/Berlin
        networks:
        - ngnix_some-net

networks:
  ngnix_some-net:
    external: true